# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "12:00"
      timezone: "Europe/Madrid"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "12:00"
      timezone: "Europe/Madrid"
    commit-message:
      prefix: "Node"
      include: "scope"
    ignore:
      - dependency-name: "autoprefixer"
    labels:
      - "node"
      - "dependencies"

  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "12:00"
      timezone: "Europe/Madrid"
    commit-message:
      prefix: "Composer"
      include: "scope"
    labels:
      - "composer"
      - "dependencies"
